[build]
builder = "DOCKERFILE"
dockerfilePath = "quickstart.Dockerfile"  # Update the dockerfilePath to "quickstart.Dockerfile"

[deploy]
numReplicas = 1
startCommand = "pip install \"argilla[server]==1.1.0\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
